async def create_order():
    try:
        pass

    except Exception as e:
        print(f'create_order.error: {e}')

async def get_order():
    try:
        pass
    except Exception as e:
        print(f'get_order.error: {e}')

async def get_orders():
    try:
        pass

    except Exception as e:
        print(f'get_order.error: {e}')

async def update_order():
    try:
        pass

    except Exception as e:
        print(f'update_order.error: {e}')

async def delete_order():
    try:
        pass
    except Exception as e:
        print(f'delete_order.error: {e}')