async def create_order_item():
    try:
        pass

    except Exception as e:
        print(f'create_order_item.error: {e}')

async def get_order_item():
    try:
        pass
    except Exception as e:
        print(f'get_order_item.error: {e}')

async def get_order_items():
    try:
        pass

    except Exception as e:
        print(f'get_order_item.error: {e}')

async def update_order_item():
    try:
        pass

    except Exception as e:
        print(f'update_order_item.error: {e}')

async def delete_order_item():
    try:
        pass
    except Exception as e:
        print(f'delete_order_item.error: {e}')